Repository Evarisk/dolicar, pull requests merged in 2023-07, with the labels that each got.

#214 #205 [RegistrationCertificate] add: digiquali controls
  class/actions_dolicar.class.php
  core/modules/modDoliCar.class.php
  langs/fr_FR/dolicar.lang
Labels: Enhancement, 3

#215 #213 [Core] fix: framework compatibility
  class/registrationcertificatefr.class.php
  dolicarindex.php
Labels: Enhancement, 2

#216 #207 [RegistrationCertificate] fix: handle all license plate formats
  core/tpl/dolicar_registrationcertificatefr_immatriculation_api_fetch_action.tpl.php
  view/registrationcertificatefr/registrationcertificatefr_card.php
Labels: Enhancement, 2

#218 #217 [Hook] fix: require lib in easycrm hook
  class/actions_dolicar.class.php
Labels: Bug, 1

#225 #224 [Mod] add: new version number 1.1.0
  .editorconfig
  README.md
  core/modules/modDoliCar.class.php
  core/triggers/interface_99_modDoliCar_DoliCarTriggers.class.php
Labels: Enhancement, 0
